version: '3'

services:
  bot:
    container_name: lynxbot
    restart: always
    command: ["./lynxbot"]
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
  db:
    image: mongo
    container_name: db
    restart: always
    ports:
      - "27017:27017"