version: '3'

services:
  bot:
    container_name: lynxbot
    restart: always
    command: ["./lynxbot"]
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - app-network

  db:
    image: mongo
    container_name: db
    restart: always
    volumes:
      - db-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: